description: Install Singularity 3.* on Debian
parameters:
  singularity-version:
    type: string
    default: 3.8.2
  machine-type:
    type: string
    default: machine
steps:
  - run:
      name: Fix cache permissions for extraction
      command: |
        NOSUDO=false
        which sudo || NOSUDO=true
        if [[ "$NOSUDO" == "false" ]]; then
            if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
        fi
        echo "$SUDO mkdir -p $HOME/singularity"
        $SUDO mkdir -p $HOME/singularity /root/singularity
        echo "$SUDO chown -R $(whoami) $HOME/singularity"
        $SUDO chown -R $(whoami) $HOME/singularity
  - restore_cache:
      keys: >-
        v3-dependencies-<< parameters.machine-type >>-<<
        parameters.singularity-version >>
  - run:
      name: install Singularity 3.* Debian Dependencies
      command: |
        if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
        $SUDO apt-get update && $SUDO apt-get install -y build-essential \
                                 squashfs-tools \
                                 libtool \
                                 uuid-dev \
                                 libssl-dev \
                                 libseccomp-dev \
                                 libgpgme11-dev \
                                 pkg-config \
                                 wget \
                                 gperf \
                                 cryptsetup-bin
  - run:
      name: Install Singularity (Version 3.* and up)
      command: >
        if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi

        # Create a directory in home for Singularity

        $SUDO mkdir -p $HOME/singularity

        SINGULARITY_PREFIX="$HOME/singularity/<< parameters.singularity-version
        >>"

        echo "export PATH='${SINGULARITY_PREFIX}/bin:$PATH'" >> "$BASH_ENV"

        if [ -f "$BASH_ENV" ]; then source $BASH_ENV; fi

        echo $PATH

        export GOPATH=/go

        if [ -d "/tmp/go/bin" ]; then export PATH=/tmp/go/bin:$PATH; fi

        if [ ! -f "${SINGULARITY_PREFIX}/bin/singularity" ]; then
          mkdir -p ${GOPATH}/src/github.com/sylabs
          cd ${GOPATH}/src/github.com/sylabs
          wget https://github.com/sylabs/singularity/releases/download/v<< parameters.singularity-version >>/singularity-ce-<< parameters.singularity-version >>.tar.gz
          tar -xzvf singularity-ce-<< parameters.singularity-version >>.tar.gz
          cd singularity-ce-<< parameters.singularity-version >> && ./mconfig -p "${SINGULARITY_PREFIX}" && make -C builddir && $SUDO make -C builddir install
        fi
  - run:
      name: Fix permissions on extracted Singularity
      command: >
        NOSUDO=false

        which sudo || NOSUDO=true

        if [[ "$NOSUDO" == "false" ]]; then
          if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
        fi

        SINGULARITY_PREFIX="$HOME/singularity/<< parameters.singularity-version
        >>"

        $SUDO chown -R root:root $HOME/singularity

        $SUDO chmod 4755
        ${SINGULARITY_PREFIX}/libexec/singularity/bin/starter-suid

        if [[ -f "/etc/sudoers" ]]; then
          $SUDO sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
        fi
  - save_cache:
      paths:
        - ~/singularity/<< parameters.singularity-version >>
      key: >-
        v3-dependencies-<< parameters.machine-type >>-<<
        parameters.singularity-version >>
