jobs:
  build:
    docker:
      - image: cimg/elixir:1.12.3-node
    steps:
      - checkout
      - run: mix --version
      - run: node --version
      - run: |
              chmod +x run.sh
              ./run.sh
