version: 2
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    parallelism: 16
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run : |
          chmod +x run.sh
          ./run.sh
 
