jobs:
  test-k3d-expose-via-proxy:
    executor: python/default
    steps:
      - setup_remote_docker
      - checkout
      - k3d/k3d-helpers
      - k3d/k3d-up:
          cluster-name: circleci-k8s-1
      - k3d/k3d-run:
          command: >
            helm repo add stable https://charts.helm.sh/stable

            helm install grafana stable/grafana

            sleep 30

            export POD_NAME=$(kubectl get pods --namespace default -l
            "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=grafana"
            -o jsonpath="{.items[0].metadata.name}")

            proxy --namespace default port-forward $POD_NAME 3000

            docker run --rm -it --network container:proxy busybox /bin/sh -c
            "wget 0.0.0.0:3000; cat index.html" | grep Grafana
          step-name: Expose service via kubectl proxy
orbs:
  k3d: devopsspiral/k3d@0.1.0
  python: circleci/python@0.3.2
version: 2.1
workflows:
  main:
    jobs:
      - test-k3d-expose-via-proxy
