version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    parallelism: 4
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run : |
      
           no_output_timeout: 40m
           command: |
                  date
                  sleep 30m
